channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.3
  - setuptools=67.8.0
  - pip=23.1.2
  - pytables=3.8.0
  - jax=0.3.25
  - pip:
      - matplotlib==3.7.0
      - deepdish==0.3.7
      - scipy==1.9.1
      - gwpopulation==0.7.0
      - json2latex==0.0.2
      - numpyro==0.10.1
      - arviz==0.14.0
      - seaborn==0.12.2
      - pandas==1.5.3
      - tabulate==0.9.0
      - TexSoup==0.3.1
      - xarray==2023.6.0
      - h5netcdf==1.2.0
      - plotly==5.18.0
      - kaleido

      